# Generated by Django 5.0 on 2023-12-20 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='estoque',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='variacao',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
    ]
